export const categories = [
  {
    id: 'laptops',
    name: 'Laptops',
    menuGroups: [
      { title: 'Brands', options: ['Dell', 'ASUS', 'Lenovo', 'HP', 'Acer'] },
      { title: 'Prices', options: ['Under 20M', '20M - 30M', '30M - 40M', 'Over 40M'] },
      { title: 'Purpose', options: ['Gaming', 'Workstation', 'Student', 'Business'] },
      { title: 'CPU', options: ['Intel Core Ultra 7', 'Intel Core i7', 'AMD Ryzen 9'] },
      { title: 'GPU', options: ['RTX 4070', 'RTX 4060', 'Integrated'] },
      { title: 'Screen', options: ['13.6 inch', '14 inch QHD', '15.6 inch FHD', '16 inch OLED'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'cpu', label: 'CPU' },
      { key: 'gpu', label: 'GPU' },
      { key: 'ram', label: 'RAM' },
      { key: 'storage', label: 'Storage' },
      { key: 'display', label: 'Display' },
      { key: 'battery', label: 'Battery' },
    ],
  },
  {
    id: 'mouse',
    name: 'Mouse',
    menuGroups: [
      { title: 'Brands', options: ['Logitech', 'Razer', 'SteelSeries', 'Corsair', 'ASUS'] },
      { title: 'Prices', options: ['Under 500K', '500K - 1M', '1M - 2M', 'Over 2M'] },
      { title: 'Purpose', options: ['Gaming', 'Office', 'Wireless', 'Ergonomic'] },
      { title: 'Sensor', options: ['Hero 25K', 'Focus Pro', 'TrueMove Air', 'PixArt 3395'] },
      { title: 'Connection', options: ['Bluetooth', '2.4GHz', 'USB-C wired'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'sensor', label: 'Sensor' },
      { key: 'dpi', label: 'DPI' },
      { key: 'connection', label: 'Connection' },
      { key: 'weight', label: 'Weight' },
    ],
  },
  {
    id: 'keyboards',
    name: 'Keyboards',
    menuGroups: [
      { title: 'Brands', options: ['Keychron', 'Logitech', 'Razer', 'Akko', 'Corsair'] },
      { title: 'Prices', options: ['Under 1M', '1M - 2M', '2M - 3M', 'Over 3M'] },
      { title: 'Purpose', options: ['Gaming', 'Office', 'Wireless', 'Compact'] },
      { title: 'Switch', options: ['Red', 'Brown', 'Blue', 'Optical'] },
      { title: 'Layout', options: ['60%', '75%', 'TKL', 'Full-size'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'switchType', label: 'Switch' },
      { key: 'layout', label: 'Layout' },
      { key: 'connection', label: 'Connection' },
      { key: 'backlight', label: 'Backlight' },
    ],
  },
  {
    id: 'monitors',
    name: 'Monitors',
    menuGroups: [
      { title: 'Brands', options: ['LG', 'Samsung', 'Dell', 'ASUS', 'AOC'] },
      { title: 'Prices', options: ['Under 4M', '4M - 7M', '7M - 12M', 'Over 12M'] },
      { title: 'Purpose', options: ['Gaming', 'Design', 'Office', 'Ultrawide'] },
      { title: 'Resolution', options: ['Full HD', 'QHD', '4K UHD', 'Ultrawide'] },
      { title: 'Refresh rate', options: ['75Hz', '144Hz', '165Hz', '240Hz'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'size', label: 'Size' },
      { key: 'resolution', label: 'Resolution' },
      { key: 'refreshRate', label: 'Refresh Rate' },
      { key: 'panel', label: 'Panel' },
    ],
  },
  {
    id: 'ssd',
    name: 'SSD',
    menuGroups: [
      { title: 'Brands', options: ['Samsung', 'WD', 'Kingston', 'Crucial', 'Seagate'] },
      { title: 'Prices', options: ['Under 1M', '1M - 2M', '2M - 4M', 'Over 4M'] },
      { title: 'Purpose', options: ['Boot drive', 'Gaming', 'Creator', 'NAS'] },
      { title: 'Capacity', options: ['500GB', '1TB', '2TB', '4TB'] },
      { title: 'Interface', options: ['SATA', 'PCIe 3.0', 'PCIe 4.0', 'PCIe 5.0'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'capacity', label: 'Capacity' },
      { key: 'interfaceType', label: 'Interface' },
      { key: 'readSpeed', label: 'Read Speed' },
      { key: 'formFactor', label: 'Form Factor' },
    ],
  },
  {
    id: 'ram',
    name: 'RAM',
    menuGroups: [
      { title: 'Brands', options: ['Corsair', 'Kingston', 'G.Skill', 'Crucial', 'TeamGroup'] },
      { title: 'Prices', options: ['Under 1M', '1M - 2M', '2M - 4M', 'Over 4M'] },
      { title: 'Purpose', options: ['Laptop upgrade', 'Gaming PC', 'Workstation', 'RGB build'] },
      { title: 'Capacity', options: ['8GB', '16GB', '32GB', '64GB'] },
      { title: 'Type', options: ['DDR4', 'DDR5', 'SODIMM'] },
      { title: 'Bus RAM', options: ['3200MHz', '3600MHz', '5200MHz', '6000MHz'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'capacity', label: 'Capacity' },
      { key: 'memoryType', label: 'Type' },
      { key: 'bus', label: 'Bus RAM' },
      { key: 'formFactor', label: 'Form Factor' },
    ],
  },
  {
    id: 'cpu',
    name: 'CPU',
    menuGroups: [
      { title: 'Brands', options: ['Intel', 'AMD'] },
      { title: 'Prices', options: ['Under 4M', '4M - 8M', '8M - 12M', 'Over 12M'] },
      { title: 'Purpose', options: ['Gaming', 'Office', 'Streaming', 'Workstation'] },
      { title: 'Socket', options: ['LGA1700', 'LGA1851', 'AM4', 'AM5'] },
      { title: 'Cores', options: ['6 cores', '8 cores', '12 cores', '16 cores'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'socket', label: 'Socket' },
      { key: 'cores', label: 'Cores' },
      { key: 'threads', label: 'Threads' },
      { key: 'tdp', label: 'TDP' },
    ],
  },
  {
    id: 'gpu',
    name: 'GPU',
    menuGroups: [
      { title: 'Brands', options: ['ASUS', 'MSI', 'Gigabyte', 'Sapphire', 'Zotac'] },
      { title: 'Prices', options: ['Under 8M', '8M - 15M', '15M - 25M', 'Over 25M'] },
      { title: 'Purpose', options: ['1080p gaming', '1440p gaming', '4K gaming', 'AI work'] },
      { title: 'Chipset', options: ['RTX 4060', 'RTX 4070 Super', 'RTX 4080', 'RX 7800 XT'] },
      { title: 'VRAM', options: ['8GB', '12GB', '16GB', '24GB'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'chipset', label: 'Chipset' },
      { key: 'vram', label: 'VRAM' },
      { key: 'power', label: 'Power' },
      { key: 'ports', label: 'Ports' },
    ],
  },
  {
    id: 'pc-case',
    name: 'PC Case',
    menuGroups: [
      { title: 'Brands', options: ['NZXT', 'Corsair', 'Lian Li', 'Cooler Master', 'DeepCool'] },
      { title: 'Prices', options: ['Under 1M', '1M - 2M', '2M - 4M', 'Over 4M'] },
      { title: 'Purpose', options: ['Compact', 'Airflow', 'Showcase', 'Silent build'] },
      { title: 'Motherboard', options: ['Mini-ITX', 'Micro-ATX', 'ATX', 'E-ATX'] },
      { title: 'Color', options: ['Black', 'White', 'Gray'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'caseType', label: 'Case Type' },
      { key: 'motherboardSupport', label: 'Mainboard Support' },
      { key: 'color', label: 'Color' },
      { key: 'fanSupport', label: 'Fan Support' },
    ],
  },
  {
    id: 'mainboard',
    name: 'Mainboard',
    menuGroups: [
      { title: 'Brands', options: ['ASUS', 'MSI', 'Gigabyte', 'ASRock', 'Biostar'] },
      { title: 'Prices', options: ['Under 3M', '3M - 5M', '5M - 8M', 'Over 8M'] },
      { title: 'Purpose', options: ['Budget PC', 'Gaming', 'Creator', 'Overclocking'] },
      { title: 'Socket', options: ['LGA1700', 'LGA1851', 'AM4', 'AM5'] },
      { title: 'Chipset', options: ['B760', 'Z790', 'B650', 'X670'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'socket', label: 'Socket' },
      { key: 'chipset', label: 'Chipset' },
      { key: 'formFactor', label: 'Form Factor' },
      { key: 'memoryType', label: 'Memory Type' },
    ],
  },
  {
    id: 'pc-fan',
    name: 'PC Fan',
    menuGroups: [
      { title: 'Brands', options: ['Noctua', 'Corsair', 'Cooler Master', 'DeepCool', 'Arctic'] },
      { title: 'Prices', options: ['Under 300K', '300K - 700K', '700K - 1.2M', 'Over 1.2M'] },
      { title: 'Purpose', options: ['Silent', 'RGB', 'Radiator', 'High airflow'] },
      { title: 'Size', options: ['120mm', '140mm', '200mm'] },
      { title: 'Bearing', options: ['Fluid dynamic', 'Magnetic levitation', 'SSO2'] },
    ],
    filters: [
      { key: 'brand', label: 'Brand' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'size', label: 'Size' },
      { key: 'speed', label: 'Speed' },
      { key: 'airflow', label: 'Airflow' },
      { key: 'lighting', label: 'Lighting' },
    ],
  },
];

export const secondaryFilterOptions = {
  laptops: {
    brand: ['Apple', 'Dell', 'ASUS', 'Lenovo', 'HP', 'Acer', 'MSI', 'Gigabyte', 'Microsoft Surface', 'LG'],
    purpose: ['Gaming', 'Workstation', 'Student', 'Business', 'Office', 'Creator', 'Thin and light', 'AI laptop'],
    cpu: [
      'Intel Core i3',
      'Intel Core i5',
      'Intel Core i7',
      'Intel Core i9',
      'Intel Core Ultra 5',
      'Intel Core Ultra 7',
      'Intel Core Ultra 9',
      'AMD Ryzen 5',
      'AMD Ryzen 7',
      'AMD Ryzen 9',
      'Apple M3',
      'Apple M4',
    ],
    gpu: [
      'Integrated',
      'Intel Arc Graphics',
      'RTX 3050',
      'RTX 4050',
      'RTX 4060',
      'RTX 4070',
      'RTX 4080',
      'RTX 4090',
      'Radeon 780M',
    ],
    ram: ['8GB', '16GB', '24GB', '32GB', '64GB'],
    storage: ['256GB SSD', '512GB SSD', '1TB SSD', '2TB SSD', '4TB SSD'],
    display: ['13.3 inch FHD', '13.6 inch Retina', '14 inch QHD', '14 inch 2.8K OLED', '15.6 inch FHD', '16 inch OLED', '17.3 inch QHD'],
    battery: ['41Wh', '52Wh', '55Wh', '65Wh', '76Wh', '90Wh', '99Wh'],
  },
  mouse: {
    brand: ['Logitech', 'Razer', 'SteelSeries', 'Corsair', 'ASUS', 'Glorious', 'Pulsar', 'Zowie'],
    purpose: ['Gaming', 'Office', 'Wireless', 'Ergonomic', 'FPS', 'MOBA', 'Travel'],
    sensor: ['Hero 25K', 'Focus Pro', 'TrueMove Air', 'PixArt 3395', 'PixArt 3370', 'ROG AimPoint'],
    dpi: ['12000 DPI', '16000 DPI', '18000 DPI', '26000 DPI', '30000 DPI', '32000 DPI', '36000 DPI'],
    connection: ['Bluetooth', '2.4GHz', 'USB-C wired', 'Tri-mode'],
    weight: ['Under 50g', '50g - 60g', '60g - 70g', '70g - 90g', 'Over 90g'],
  },
  keyboards: {
    brand: ['Keychron', 'Logitech', 'Razer', 'Akko', 'Corsair', 'Ducky', 'Leopold', 'ASUS'],
    purpose: ['Gaming', 'Office', 'Wireless', 'Compact', 'Creator', 'Typing'],
    switchType: ['Red', 'Brown', 'Blue', 'Silver', 'Optical', 'Magnetic', 'Low profile'],
    layout: ['60%', '65%', '75%', 'TKL', 'Full-size', 'Alice'],
    connection: ['Bluetooth', '2.4GHz', 'USB-C wired', 'Tri-mode'],
    backlight: ['None', 'White', 'RGB', 'Per-key RGB'],
  },
  monitors: {
    brand: ['LG', 'Samsung', 'Dell', 'ASUS', 'AOC', 'MSI', 'Gigabyte', 'BenQ'],
    purpose: ['Gaming', 'Design', 'Office', 'Ultrawide', 'Console', 'Programming'],
    size: ['24 inch', '25 inch', '27 inch', '32 inch', '34 inch', '49 inch'],
    resolution: ['Full HD', 'QHD', '4K UHD', '5K', 'Ultrawide', 'Super Ultrawide'],
    refreshRate: ['60Hz', '75Hz', '100Hz', '144Hz', '165Hz', '180Hz', '240Hz', '360Hz'],
    panel: ['IPS', 'Nano IPS', 'IPS Black', 'VA', 'OLED', 'QD-OLED', 'TN'],
  },
  ssd: {
    brand: ['Samsung', 'WD', 'Kingston', 'Crucial', 'Seagate', 'Lexar', 'ADATA', 'Corsair'],
    purpose: ['Boot drive', 'Gaming', 'Creator', 'NAS', 'Portable', 'PS5 upgrade'],
    capacity: ['250GB', '500GB', '1TB', '2TB', '4TB', '8TB'],
    interfaceType: ['SATA', 'PCIe 3.0', 'PCIe 4.0', 'PCIe 5.0', 'USB 3.2'],
    readSpeed: ['560MB/s', '3500MB/s', '5000MB/s', '7000MB/s', '7450MB/s', '10000MB/s', '12000MB/s'],
    formFactor: ['2.5 inch', 'M.2 2230', 'M.2 2242', 'M.2 2280', 'External'],
  },
  ram: {
    brand: ['Corsair', 'Kingston', 'G.Skill', 'Crucial', 'TeamGroup', 'ADATA', 'Patriot'],
    purpose: ['Laptop upgrade', 'Gaming PC', 'Workstation', 'RGB build', 'Office PC'],
    capacity: ['8GB', '16GB', '32GB', '48GB', '64GB', '96GB', '128GB'],
    memoryType: ['DDR3', 'DDR4', 'DDR5', 'LPDDR5', 'SODIMM'],
    bus: ['2666MHz', '3200MHz', '3600MHz', '4800MHz', '5200MHz', '5600MHz', '6000MHz', '6400MHz', '7200MHz'],
    formFactor: ['DIMM', 'SODIMM', 'CAMM2'],
  },
  cpu: {
    brand: ['Intel', 'AMD'],
    purpose: ['Gaming', 'Office', 'Streaming', 'Workstation', 'Budget PC', 'Creator'],
    socket: ['LGA1200', 'LGA1700', 'LGA1851', 'AM4', 'AM5', 'sTRX4'],
    cores: ['4 cores', '6 cores', '8 cores', '10 cores', '12 cores', '14 cores', '16 cores', '24 cores', '32 cores'],
    threads: ['8 threads', '12 threads', '16 threads', '20 threads', '24 threads', '28 threads', '32 threads', '64 threads'],
    tdp: ['35W', '65W', '95W', '105W', '120W', '125W', '170W', '280W'],
  },
  gpu: {
    brand: ['ASUS', 'MSI', 'Gigabyte', 'Sapphire', 'Zotac', 'PNY', 'PowerColor', 'Galax'],
    purpose: ['1080p gaming', '1440p gaming', '4K gaming', 'AI work', 'Streaming', 'Creator'],
    chipset: ['RTX 3050', 'RTX 4060', 'RTX 4060 Ti', 'RTX 4070', 'RTX 4070 Super', 'RTX 4080', 'RTX 4090', 'RX 7600', 'RX 7700 XT', 'RX 7800 XT', 'RX 7900 XTX'],
    vram: ['6GB', '8GB', '10GB', '12GB', '16GB', '20GB', '24GB'],
    power: ['115W', '160W', '200W', '220W', '263W', '320W', '355W', '450W'],
    ports: ['HDMI, DisplayPort', 'HDMI, 3x DisplayPort', '2x HDMI, 2x DisplayPort', 'USB-C, HDMI, DisplayPort'],
  },
  'pc-case': {
    brand: ['NZXT', 'Corsair', 'Lian Li', 'Cooler Master', 'DeepCool', 'Fractal Design', 'Phanteks'],
    purpose: ['Compact', 'Airflow', 'Showcase', 'Silent build', 'Water cooling', 'Budget build'],
    caseType: ['Mini tower', 'Mid tower', 'Full tower', 'Open frame'],
    motherboardSupport: ['Mini-ITX', 'Micro-ATX', 'ATX', 'E-ATX'],
    color: ['Black', 'White', 'Gray', 'Silver'],
    fanSupport: ['3 fans', '5 fans', '6 fans', '8 fans', '9 fans', '10 fans', '12 fans'],
  },
  mainboard: {
    brand: ['ASUS', 'MSI', 'Gigabyte', 'ASRock', 'Biostar', 'NZXT'],
    purpose: ['Budget PC', 'Gaming', 'Creator', 'Overclocking', 'Workstation', 'Small form factor'],
    socket: ['LGA1200', 'LGA1700', 'LGA1851', 'AM4', 'AM5'],
    chipset: ['H610', 'B660', 'B760', 'Z790', 'A520', 'B550', 'X570', 'A620', 'B650', 'X670'],
    formFactor: ['Mini-ITX', 'Micro-ATX', 'ATX', 'E-ATX'],
    memoryType: ['DDR4', 'DDR5'],
  },
  'pc-fan': {
    brand: ['Noctua', 'Corsair', 'Cooler Master', 'DeepCool', 'Arctic', 'Lian Li', 'Thermaltake'],
    purpose: ['Silent', 'RGB', 'Radiator', 'High airflow', 'Static pressure', 'Budget cooling'],
    size: ['80mm', '92mm', '120mm', '140mm', '200mm'],
    speed: ['1200 RPM', '1500 RPM', '1700 RPM', '1800 RPM', '1850 RPM', '2000 RPM', '2100 RPM', '3000 RPM'],
    airflow: ['40 CFM', '50 CFM', '60 CFM', '62 CFM', '65 CFM', '68 CFM', '72 CFM', '90 CFM'],
    lighting: ['None', 'White LED', 'RGB', 'ARGB'],
  },
};

const productImages = {
  laptops: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80',
  mouse: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=900&q=80',
  keyboards: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=900&q=80',
  monitors: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=900&q=80',
  ssd: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=900&q=80',
  ram: 'https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=900&q=80',
  cpu: 'https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=900&q=80',
  gpu: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=80',
  'pc-case': 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=900&q=80',
  mainboard: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80',
  'pc-fan': 'https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?auto=format&fit=crop&w=900&q=80',
};

export const products = [
  makeProduct(1, 'laptops', 'Dell XPS 13 Plus', 'Dell', 32990000, 'Top seller', {
    purpose: 'Business',
    cpu: 'Intel Core Ultra 7',
    gpu: 'Integrated',
    ram: '16GB',
    storage: '1TB SSD',
    display: '13.4 inch 3.5K OLED',
    battery: '55Wh',
  }),
  makeProduct(2, 'laptops', 'ASUS ROG Zephyrus G14', 'ASUS', 42990000, 'Gaming pick', {
    purpose: 'Gaming',
    cpu: 'AMD Ryzen 9',
    gpu: 'RTX 4070',
    ram: '32GB',
    storage: '1TB SSD',
    display: '14 inch QHD 165Hz',
    battery: '76Wh',
  }),
  makeProduct(3, 'laptops', 'Lenovo ThinkPad P16', 'Lenovo', 46990000, 'Workstation', {
    purpose: 'Workstation',
    cpu: 'Intel Core i7',
    gpu: 'RTX 4060',
    ram: '32GB',
    storage: '2TB SSD',
    display: '16 inch OLED',
    battery: '90Wh',
  }),
  makeProduct(4, 'laptops', 'HP Pavilion 15', 'HP', 16990000, 'Best value', {
    purpose: 'Student',
    cpu: 'Intel Core i5',
    gpu: 'Integrated',
    ram: '8GB',
    storage: '512GB SSD',
    display: '15.6 inch FHD',
    battery: '41Wh',
  }),
  makeProduct(5, 'laptops', 'Acer Swift Go 14', 'Acer', 21990000, 'OLED value', {
    purpose: 'Student',
    cpu: 'Intel Core Ultra 5',
    gpu: 'Integrated',
    ram: '16GB',
    storage: '512GB SSD',
    display: '14 inch 2.8K OLED',
    battery: '65Wh',
  }),
  makeProduct(6, 'mouse', 'Logitech G Pro X Superlight 2', 'Logitech', 3290000, 'Esports', {
    purpose: 'Gaming',
    sensor: 'Hero 25K',
    dpi: '32000 DPI',
    connection: '2.4GHz',
    weight: '60g',
  }),
  makeProduct(7, 'mouse', 'Razer DeathAdder V3 Pro', 'Razer', 3490000, 'Ergonomic', {
    purpose: 'Gaming',
    sensor: 'Focus Pro',
    dpi: '30000 DPI',
    connection: '2.4GHz',
    weight: '63g',
  }),
  makeProduct(8, 'mouse', 'SteelSeries Aerox 5 Wireless', 'SteelSeries', 2490000, 'Lightweight', {
    purpose: 'Wireless',
    sensor: 'TrueMove Air',
    dpi: '18000 DPI',
    connection: 'Bluetooth',
    weight: '74g',
  }),
  makeProduct(9, 'mouse', 'Corsair Katar Elite Wireless', 'Corsair', 1590000, 'Compact', {
    purpose: 'Office',
    sensor: 'PixArt 3395',
    dpi: '26000 DPI',
    connection: '2.4GHz',
    weight: '69g',
  }),
  makeProduct(10, 'mouse', 'ASUS ROG Keris AimPoint', 'ASUS', 2190000, 'FPS ready', {
    purpose: 'Gaming',
    sensor: 'ROG AimPoint',
    dpi: '36000 DPI',
    connection: 'USB-C wired',
    weight: '75g',
  }),
  makeProduct(11, 'keyboards', 'Keychron K2 Pro', 'Keychron', 2490000, 'Wireless', {
    purpose: 'Office',
    switchType: 'Brown',
    layout: '75%',
    connection: 'Bluetooth',
    backlight: 'RGB',
  }),
  makeProduct(12, 'keyboards', 'Logitech G Pro X TKL', 'Logitech', 3290000, 'Tournament', {
    purpose: 'Gaming',
    switchType: 'Red',
    layout: 'TKL',
    connection: '2.4GHz',
    backlight: 'RGB',
  }),
  makeProduct(13, 'keyboards', 'Razer Huntsman Mini', 'Razer', 2590000, 'Compact', {
    purpose: 'Gaming',
    switchType: 'Optical',
    layout: '60%',
    connection: 'USB-C wired',
    backlight: 'RGB',
  }),
  makeProduct(14, 'keyboards', 'Akko 5075B Plus', 'Akko', 1990000, 'Hot-swap', {
    purpose: 'Compact',
    switchType: 'Blue',
    layout: '75%',
    connection: 'Bluetooth',
    backlight: 'RGB',
  }),
  makeProduct(15, 'keyboards', 'Corsair K70 RGB Pro', 'Corsair', 3490000, 'Full-size', {
    purpose: 'Gaming',
    switchType: 'Red',
    layout: 'Full-size',
    connection: 'USB-C wired',
    backlight: 'RGB',
  }),
  makeProduct(16, 'monitors', 'LG UltraGear 27GP850', 'LG', 7290000, 'QHD gaming', {
    purpose: 'Gaming',
    size: '27 inch',
    resolution: 'QHD',
    refreshRate: '165Hz',
    panel: 'Nano IPS',
  }),
  makeProduct(17, 'monitors', 'Samsung Odyssey G5 32', 'Samsung', 6790000, 'Curved', {
    purpose: 'Gaming',
    size: '32 inch',
    resolution: 'QHD',
    refreshRate: '144Hz',
    panel: 'VA',
  }),
  makeProduct(18, 'monitors', 'Dell UltraSharp U2723QE', 'Dell', 12990000, 'Creator', {
    purpose: 'Design',
    size: '27 inch',
    resolution: '4K UHD',
    refreshRate: '60Hz',
    panel: 'IPS Black',
  }),
  makeProduct(19, 'monitors', 'ASUS ProArt PA278QV', 'ASUS', 6990000, 'Color work', {
    purpose: 'Design',
    size: '27 inch',
    resolution: 'QHD',
    refreshRate: '75Hz',
    panel: 'IPS',
  }),
  makeProduct(20, 'monitors', 'AOC 24G2SP', 'AOC', 3990000, 'Budget gaming', {
    purpose: 'Gaming',
    size: '24 inch',
    resolution: 'Full HD',
    refreshRate: '165Hz',
    panel: 'IPS',
  }),
  makeProduct(21, 'ssd', 'Samsung 990 Pro 1TB', 'Samsung', 2890000, 'PCIe 4.0', {
    purpose: 'Gaming',
    capacity: '1TB',
    interfaceType: 'PCIe 4.0',
    readSpeed: '7450MB/s',
    formFactor: 'M.2 2280',
  }),
  makeProduct(22, 'ssd', 'WD Black SN850X 2TB', 'WD', 4590000, 'High speed', {
    purpose: 'Creator',
    capacity: '2TB',
    interfaceType: 'PCIe 4.0',
    readSpeed: '7300MB/s',
    formFactor: 'M.2 2280',
  }),
  makeProduct(23, 'ssd', 'Kingston NV2 1TB', 'Kingston', 1490000, 'Budget NVMe', {
    purpose: 'Boot drive',
    capacity: '1TB',
    interfaceType: 'PCIe 3.0',
    readSpeed: '3500MB/s',
    formFactor: 'M.2 2280',
  }),
  makeProduct(24, 'ssd', 'Crucial MX500 1TB', 'Crucial', 1690000, 'SATA reliable', {
    purpose: 'Boot drive',
    capacity: '1TB',
    interfaceType: 'SATA',
    readSpeed: '560MB/s',
    formFactor: '2.5 inch',
  }),
  makeProduct(25, 'ssd', 'Seagate FireCuda 540 2TB', 'Seagate', 6290000, 'PCIe 5.0', {
    purpose: 'Creator',
    capacity: '2TB',
    interfaceType: 'PCIe 5.0',
    readSpeed: '10000MB/s',
    formFactor: 'M.2 2280',
  }),
  makeProduct(26, 'ram', 'Corsair Vengeance DDR5 32GB', 'Corsair', 2990000, 'DDR5 kit', {
    purpose: 'Gaming PC',
    capacity: '32GB',
    memoryType: 'DDR5',
    bus: '6000MHz',
    formFactor: 'DIMM',
  }),
  makeProduct(27, 'ram', 'Kingston Fury Beast 16GB', 'Kingston', 1290000, 'Gaming value', {
    purpose: 'Gaming PC',
    capacity: '16GB',
    memoryType: 'DDR4',
    bus: '3200MHz',
    formFactor: 'DIMM',
  }),
  makeProduct(28, 'ram', 'G.Skill Trident Z5 RGB 32GB', 'G.Skill', 3490000, 'RGB build', {
    purpose: 'RGB build',
    capacity: '32GB',
    memoryType: 'DDR5',
    bus: '6000MHz',
    formFactor: 'DIMM',
  }),
  makeProduct(29, 'ram', 'Crucial Laptop DDR4 16GB', 'Crucial', 990000, 'Laptop upgrade', {
    purpose: 'Laptop upgrade',
    capacity: '16GB',
    memoryType: 'DDR4',
    bus: '3200MHz',
    formFactor: 'SODIMM',
  }),
  makeProduct(30, 'ram', 'TeamGroup Elite DDR5 16GB', 'TeamGroup', 1490000, 'DDR5 value', {
    purpose: 'Laptop upgrade',
    capacity: '16GB',
    memoryType: 'DDR5',
    bus: '5200MHz',
    formFactor: 'SODIMM',
  }),
  makeProduct(31, 'cpu', 'Intel Core i5-14600K', 'Intel', 7890000, 'Gaming value', {
    purpose: 'Gaming',
    socket: 'LGA1700',
    cores: '14 cores',
    threads: '20 threads',
    tdp: '125W',
  }),
  makeProduct(32, 'cpu', 'Intel Core i7-14700K', 'Intel', 11290000, 'Creator pick', {
    purpose: 'Streaming',
    socket: 'LGA1700',
    cores: '20 cores',
    threads: '28 threads',
    tdp: '125W',
  }),
  makeProduct(33, 'cpu', 'AMD Ryzen 5 7600', 'AMD', 4990000, 'AM5 value', {
    purpose: 'Office',
    socket: 'AM5',
    cores: '6 cores',
    threads: '12 threads',
    tdp: '65W',
  }),
  makeProduct(34, 'cpu', 'AMD Ryzen 7 7800X3D', 'AMD', 9690000, 'Gaming king', {
    purpose: 'Gaming',
    socket: 'AM5',
    cores: '8 cores',
    threads: '16 threads',
    tdp: '120W',
  }),
  makeProduct(35, 'cpu', 'AMD Ryzen 9 7950X', 'AMD', 13990000, 'Workstation', {
    purpose: 'Workstation',
    socket: 'AM5',
    cores: '16 cores',
    threads: '32 threads',
    tdp: '170W',
  }),
  makeProduct(36, 'gpu', 'ASUS Dual RTX 4060 OC', 'ASUS', 7990000, '1080p', {
    purpose: '1080p gaming',
    chipset: 'RTX 4060',
    vram: '8GB',
    power: '115W',
    ports: 'HDMI, DisplayPort',
  }),
  makeProduct(37, 'gpu', 'MSI RTX 4070 Super Gaming X', 'MSI', 17990000, '1440p', {
    purpose: '1440p gaming',
    chipset: 'RTX 4070 Super',
    vram: '12GB',
    power: '220W',
    ports: 'HDMI, 3x DisplayPort',
  }),
  makeProduct(38, 'gpu', 'Gigabyte RTX 4080 Super Aero', 'Gigabyte', 31990000, '4K', {
    purpose: '4K gaming',
    chipset: 'RTX 4080',
    vram: '16GB',
    power: '320W',
    ports: 'HDMI, 3x DisplayPort',
  }),
  makeProduct(39, 'gpu', 'Sapphire Pulse RX 7800 XT', 'Sapphire', 13990000, 'Radeon value', {
    purpose: '1440p gaming',
    chipset: 'RX 7800 XT',
    vram: '16GB',
    power: '263W',
    ports: 'HDMI, DisplayPort',
  }),
  makeProduct(40, 'gpu', 'Zotac RTX 4090 Trinity', 'Zotac', 46990000, 'AI work', {
    purpose: 'AI work',
    chipset: 'RTX 4090',
    vram: '24GB',
    power: '450W',
    ports: 'HDMI, 3x DisplayPort',
  }),
  makeProduct(41, 'pc-case', 'NZXT H5 Flow', 'NZXT', 2190000, 'Airflow', {
    purpose: 'Airflow',
    caseType: 'Mid tower',
    motherboardSupport: 'ATX',
    color: 'Black',
    fanSupport: '6 fans',
  }),
  makeProduct(42, 'pc-case', 'Corsair 4000D Airflow', 'Corsair', 2490000, 'Clean build', {
    purpose: 'Airflow',
    caseType: 'Mid tower',
    motherboardSupport: 'ATX',
    color: 'White',
    fanSupport: '6 fans',
  }),
  makeProduct(43, 'pc-case', 'Lian Li O11 Dynamic EVO', 'Lian Li', 3990000, 'Showcase', {
    purpose: 'Showcase',
    caseType: 'Mid tower',
    motherboardSupport: 'E-ATX',
    color: 'White',
    fanSupport: '10 fans',
  }),
  makeProduct(44, 'pc-case', 'Cooler Master NR200P', 'Cooler Master', 2390000, 'Mini ITX', {
    purpose: 'Compact',
    caseType: 'Mini tower',
    motherboardSupport: 'Mini-ITX',
    color: 'Black',
    fanSupport: '5 fans',
  }),
  makeProduct(45, 'pc-case', 'DeepCool CH560 Digital', 'DeepCool', 2890000, 'Display panel', {
    purpose: 'Showcase',
    caseType: 'Mid tower',
    motherboardSupport: 'ATX',
    color: 'Black',
    fanSupport: '9 fans',
  }),
  makeProduct(46, 'mainboard', 'ASUS TUF Gaming B650-Plus', 'ASUS', 5290000, 'AM5 durable', {
    purpose: 'Gaming',
    socket: 'AM5',
    chipset: 'B650',
    formFactor: 'ATX',
    memoryType: 'DDR5',
  }),
  makeProduct(47, 'mainboard', 'MSI MAG B760 Tomahawk WiFi', 'MSI', 4890000, 'Intel value', {
    purpose: 'Gaming',
    socket: 'LGA1700',
    chipset: 'B760',
    formFactor: 'ATX',
    memoryType: 'DDR5',
  }),
  makeProduct(48, 'mainboard', 'Gigabyte Z790 Aorus Elite AX', 'Gigabyte', 7190000, 'Overclock', {
    purpose: 'Overclocking',
    socket: 'LGA1700',
    chipset: 'Z790',
    formFactor: 'ATX',
    memoryType: 'DDR5',
  }),
  makeProduct(49, 'mainboard', 'ASRock B550M Steel Legend', 'ASRock', 2890000, 'AM4 value', {
    purpose: 'Budget PC',
    socket: 'AM4',
    chipset: 'B550',
    formFactor: 'Micro-ATX',
    memoryType: 'DDR4',
  }),
  makeProduct(50, 'mainboard', 'Biostar B650MT', 'Biostar', 3290000, 'Budget AM5', {
    purpose: 'Budget PC',
    socket: 'AM5',
    chipset: 'B650',
    formFactor: 'Micro-ATX',
    memoryType: 'DDR5',
  }),
  makeProduct(51, 'pc-fan', 'Noctua NF-A12x25 PWM', 'Noctua', 890000, 'Silent', {
    purpose: 'Silent',
    size: '120mm',
    speed: '2000 RPM',
    airflow: '60 CFM',
    lighting: 'None',
  }),
  makeProduct(52, 'pc-fan', 'Corsair iCUE AF120 RGB Elite', 'Corsair', 690000, 'RGB', {
    purpose: 'RGB',
    size: '120mm',
    speed: '2100 RPM',
    airflow: '65 CFM',
    lighting: 'RGB',
  }),
  makeProduct(53, 'pc-fan', 'Cooler Master SickleFlow 120', 'Cooler Master', 290000, 'Budget RGB', {
    purpose: 'RGB',
    size: '120mm',
    speed: '1800 RPM',
    airflow: '62 CFM',
    lighting: 'RGB',
  }),
  makeProduct(54, 'pc-fan', 'DeepCool FK120', 'DeepCool', 350000, 'Radiator', {
    purpose: 'Radiator',
    size: '120mm',
    speed: '1850 RPM',
    airflow: '68 CFM',
    lighting: 'None',
  }),
  makeProduct(55, 'pc-fan', 'Arctic P14 PWM PST', 'Arctic', 390000, '140mm airflow', {
    purpose: 'High airflow',
    size: '140mm',
    speed: '1700 RPM',
    airflow: '72 CFM',
    lighting: 'None',
  }),
];

export const priceRanges = [
  { label: 'All prices', min: 0, max: Number.POSITIVE_INFINITY },
  { label: 'Under 300K', min: 0, max: 300000 },
  { label: '300K - 700K', min: 300000, max: 700000 },
  { label: '700K - 1.2M', min: 700000, max: 1200000 },
  { label: 'Under 500K', min: 0, max: 500000 },
  { label: '500K - 1M', min: 500000, max: 1000000 },
  { label: 'Under 1M', min: 0, max: 1000000 },
  { label: '1M - 2M', min: 1000000, max: 2000000 },
  { label: '1M - 5M', min: 1000000, max: 5000000 },
  { label: '2M - 3M', min: 2000000, max: 3000000 },
  { label: '2M - 4M', min: 2000000, max: 4000000 },
  { label: '3M - 5M', min: 3000000, max: 5000000 },
  { label: '4M - 7M', min: 4000000, max: 7000000 },
  { label: '4M - 8M', min: 4000000, max: 8000000 },
  { label: '5M - 8M', min: 5000000, max: 8000000 },
  { label: '5M - 15M', min: 5000000, max: 15000000 },
  { label: '7M - 12M', min: 7000000, max: 12000000 },
  { label: '8M - 12M', min: 8000000, max: 12000000 },
  { label: '8M - 15M', min: 8000000, max: 15000000 },
  { label: '10M - 15M', min: 10000000, max: 15000000 },
  { label: '15M - 20M', min: 15000000, max: 20000000 },
  { label: '15M - 25M', min: 15000000, max: 25000000 },
  { label: '15M - 30M', min: 15000000, max: 30000000 },
  { label: '20M - 30M', min: 20000000, max: 30000000 },
  { label: '20M - 25M', min: 20000000, max: 25000000 },
  { label: '25M - 30M', min: 25000000, max: 30000000 },
  { label: '30M - 40M', min: 30000000, max: 40000000 },
  { label: 'Under 3M', min: 0, max: 3000000 },
  { label: 'Under 4M', min: 0, max: 4000000 },
  { label: 'Under 8M', min: 0, max: 8000000 },
  { label: 'Under 10M', min: 0, max: 10000000 },
  { label: 'Under 20M', min: 0, max: 20000000 },
  { label: 'Over 1.2M', min: 1200000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 2M', min: 2000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 3M', min: 3000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 4M', min: 4000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 8M', min: 8000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 12M', min: 12000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 25M', min: 25000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 30M', min: 30000000, max: Number.POSITIVE_INFINITY },
  { label: 'Over 40M', min: 40000000, max: Number.POSITIVE_INFINITY },
];

export const sortOptions = [
  { label: 'Recommended', value: 'recommended' },
  { label: 'Price low to high', value: 'price-asc' },
  { label: 'Price high to low', value: 'price-desc' },
];

export function formatPrice(price) {
  return new Intl.NumberFormat('vi-VN', {
    style: 'currency',
    currency: 'VND',
    maximumFractionDigits: 0,
  }).format(price);
}

export function getAverageRating(product) {
  const total = product.reviews.reduce((sum, review) => sum + review.rating, 0);
  return (total / product.reviews.length).toFixed(1);
}

export function getCategoryById(categoryId) {
  return categories.find((category) => category.id === categoryId);
}

function makeProduct(id, categoryId, name, brand, price, badge, specs) {
  const category = categories.find((item) => item.id === categoryId);

  return {
    id,
    categoryId,
    category: category.name,
    name,
    brand,
    price,
    badge,
    specs,
    stock: id % 9 === 0 ? 0 : 5 + (id % 12),
    image: productImages[categoryId],
    warranty: categoryId === 'laptops' ? '24 months official warranty' : '12 months official warranty',
    description: `${name} is a ${badge.toLowerCase()} ${category.name.toLowerCase()} option for ${specs.purpose.toLowerCase()} users.`,
    reviews: [
      {
        user: 'Minh Anh',
        rating: 4 + (id % 2),
        date: '2026-05-12',
        comment: `Good ${category.name.toLowerCase()} for the price. The specifications match my current setup.`,
      },
      {
        user: 'Hoang Nam',
        rating: 4,
        date: '2026-05-18',
        comment: 'Delivery was quick and the product information was easy to compare before buying.',
      },
    ],
  };
}
